version: "3"

services:
  amp-regression-predict-flask:
    build:
      context: .
    ports:
      - 8889:8888
    volumes:
      - .:/app
    restart: always
    # command: flask run --host=0.0.0.0 --port=8888 --reload --debugger
    command: gunicorn app:app --workers 1 --bind 0.0.0.0:8888 --timeout 1800
    networks:
      - amp-regression-predict-flask
    # env_file: .env

networks:
  amp-regression-predict-flask:
    external: true